version: "3.9"
services: 
    jenkins:
        container_name: "jenkins-localhost"
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./Dockerfile
        ports: 
            - 8080:8080
            - 50000:50000
        volumes: 
            - ./jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock